config/routes.rb
Rails.application.routes.draw do
  get 'courses/show'
  get 'courses/archive'


  get 'users/:id/courses', {to: 'users#courses'}
  
  root to: "home#index"
  get 'home/index'

  resources :assignments

  resources :courses do
    resources :course_assignments do
      resources :submissions do
        get "new_grade"
        post "create_grade"
        get "edit_grade"
        patch "update_grade"
        delete "destroy_grade"
      end
    end 
    post "add_attendance"
    end

  resources :users

  get '/users/:id/courses/', {to: "courses#index"}
  get '/users/:id/assignments/', {to: "due_assignments#index"}

  get '/users/:id/submitted_assignments/', {to: "users#submitted_assignments"}
  get '/users/:id/due_assignments/', {to: "users#due_assignments"}

  get '/users/:id/new_role', to: "users#new_role", as: :new_role
  post 'users/:id/create_role', to: "users#create_role", as: :create_role

  resources :assignments

  resources :sessions, only: [:create, :destroy, :new]

  resources :users, only: [:new, :create, :edit, :update, :destroy]

  get '/users/:id/password', { to: "users#password", as: 'password' }
  post '/users/:id/password', { to: "users#update_password", as: 'update_password' }

  get "login", to: "sessions#new"
  get "sign_in", to: "sessions#new"

  get "admin/courses"
  get "admin/users"
  get "admin/archive"

end

app/models/course_assignment.rb
class CourseAssignment < ApplicationRecord
  has_many :submissions, dependent: :destroy

  belongs_to :course
  belongs_to :assignment
  
  before_validation :set_default_is_active

  # Returns the assignments that have been assigned and are past due
  def self.past
    CourseAssignment.where("assign_date < ? AND due_date < ?", Time.now, Time.now).order(:due_date)
  end

  # Return the assignments that haven't been assigned yet
  def self.upcoming
    CourseAssignment.where("assign_date > ?", Time.now).order(:due_date)
  end

  # Return the assignments that are due and
  def self.pending
    CourseAssignment.where("assign_date < ? AND due_date > ?", Time.now, Time.now).order(:due_date)
  end

  private

  def set_default_is_active
    self.is_active ||= true
  end
end

app/controllers/course_assignments_controller.rb
class CourseAssignmentsController < ApplicationController
    before_action :find_course_assignment, only: [:show, :edit, :update, :destroy]

    def index
        @course = Course.find(params[:course_id])
    end

    def new 
        @course = Course.find(params[:course_id])
        @assignments = Assignment.all.select do |assignment|
            true
            # !(@course_assignment.course.course_assignments.map(&:id).include? assignment.id)
        end
        @course_assignment = CourseAssignment.new due_date: Time.now + 1.days
    end
    
    def create
        @course = Course.find(params[:course_id])
        @course_assignment = CourseAssignment.new(params.require(:course_assignment).permit(:due_date, :assignment_id, :is_active))
        @course_assignment.course = @course
        @course_assignment.assign_date = DateTime.now
        if @course_assignment.save
            redirect_to :root
        else
            render :new
        end
    end

    def edit
        @course = Course.find(params[:course_id])
        @assignments = Assignment.all
    end

    def update
        @course = Course.find(params[:course_id])
        if @course_assignment.update(params.require(:course_assignment).permit(:due_date, :assignment_id, :is_active))
            redirect_to course_course_assignment_path(@course, @course_assignment)
        else
            render :edit
        end
    end

    def destroy
        if @course_assignment.destroy
            redirect_to @course_assignment.course
        else
            redirect_to @course_assignment
        end
    end

    def show
    end 

    private
    def find_course_assignment
        @course_assignment = CourseAssignment.find(params[:id])
    end

end

app/views/course_assignments/edit.html.erb
<article className="new-course-assignment">

    <h1>Edit an assignment in <%= @course.name %></h1>

    <%= form_for([@course, @course_assignment], name: :assignment_id) do |f| %>
        <select id="assignment-select" name="course_assignment[assignment_id]">
            <option>Select one...</option>
            <%= @assignments.map do |assignment| %>
                <option id='select-<%= assignment.id %>'value=<%= assignment.id %> data-assignment='<%= JSON.dump(assignment.attributes.to_options) %>' <%= @course_assignment.assignment.id == assignment.id ? "selected" : "" %> ><%= assignment.name %></option>
            <% end %>
        </select>

        <div class="assignment-info">
            <!-- Dynamically filled -->
        </div>

        <div>
            <%= f.label :due_date %>
            <%= f.datetime_select :due_date, prompt: true %>
        </div>

        <div>
            <!-- The 'title' attribute is what shows up when you hover over an element -->
            <%= f.label :is_active %><i class="fas fa-question-circle" title="If the assignment is active, student will be able to view and submit to the assignment."></i>
            <%= f.check_box :is_active %>
        </div>

        <%= f.submit "Update!",class:"ui primary button" %>
    <% end %>

</article>

<script>
    document.addEventListener('DOMContentLoaded', () => {

        let assignment = JSON.parse(document.querySelector("[selected]").dataset.assignment)

        document.querySelector(".assignment-info").innerHTML = `
            <h2>${assignment.name}</h2>
            <p>${assignment.description}</p>
        `

        document.getElementById("assignment-select").addEventListener("change", (event) => {
            if (document.getElementById(`select-${event.target.value}`)) {
                let assignment = JSON.parse(document.getElementById(`select-${event.target.value}`).dataset.assignment)

                document.querySelector(".assignment-info").innerHTML = `
                    <h2>${assignment.name}</h2>
                    <p>${assignment.description}</p>
                `
            }
        })
    }, false);

</script>

app/views/course_assignments/index.html.erb
<article class="show-course-assignment">
  <div class='card-tier'>
    <div class="card">
      <div class='card-header'>
        <h2>Pending Assignments</h2>
      </div>
      <div class='panel-container'>
        <% CourseAssignment.pending.where(course_id: @course.id).each do |assignment| %>
        <div class='card-content'>
          <h2>Assignment: <%= assignment.assignment.name %></h2>
          <h3>Course: <%= assignment.course.name %></h3>
          <h3>
            <% if assignment.due_date > Time.now %>
              <p>Due in <%= distance_of_time_in_words(Time.now, assignment.due_date) %> </p>
            <% else %>
              <p>Due <%= assignment.due_date %> ago</p>
            <% end %>
          </h3>
          <div class='button'>
            <%= link_to 'View details...', course_course_assignment_path(assignment.course, assignment) %>
          </div>
        </div>
      <% end %>
      </div>
    </div>
    <div class="card">
      <div class='card-header'>
        <h2>Upcoming Assignments</h2>
      </div>
      <div class='panel-container'>
        <% CourseAssignment.upcoming.where(course_id: @course.id)&.each do |assignment| %>
        <div class='card-content'>
          <h2>Assignment: <%= assignment.assignment.name %></h2>
          <h3>Course: <%= assignment.course.name %></h3>
          <h3>
            <% if assignment.due_date > Time.now %>
              <p>Due in <%= distance_of_time_in_words(Time.now, assignment.due_date) %> </p>
            <% else %>
              <p>Due <%= assignment.due_date %> ago</p>
            <% end %>
          </h3>
          <div class='button'>
            <%= link_to 'View details...', course_course_assignment_path(assignment.course, assignment) %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class='card-tier'>
    <div class="card">
      <div class='card-header'>
        <h2>Past Assignments</h2>
      </div>
      <% CourseAssignment.past.where(course_id: @course.id).each do |assignment| %>
      <div class='card-content'>
        <h2>Assignment: <%= assignment.assignment.name %></h2>
        <h3>Course: <%= assignment.course.name %></h3>
        <h3>
          <% if assignment.due_date > Time.now %>
            <p>Due in <%= distance_of_time_in_words(Time.now, assignment.due_date) %> </p>
          <% else %>
            <p>Due <%= assignment.due_date %> ago</p>
          <% end %>
        </h3>
        <div class='button'>
          <%= link_to 'View details...', course_course_assignment_path(assignment.course, assignment) %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</article>

app/views/course_assignments/new.html.erb
<article className="new-course-assignment">

    <h1>Post Assignment to <%= @course.name %></h1>

    <%= form_for([@course, @course_assignment], name: :assignment_id) do |f| %>
        <select id="assignment-select" name="course_assignment[assignment_id]">
            <option>Select one...</option>
            <%= @assignments.map do |assignment| %>
                <option id='select-<%= assignment.id %>'value=<%= assignment.id %> data-assignment='<%= JSON.dump(assignment.attributes.to_options) %>' ><%= assignment.name %></option>
            <% end %>
        </select>

        <div class="assignment-info">
            <!-- Dynamically filled -->
        </div>

        <div>
            <%= f.label :due_date %>
            <%= f.datetime_select :due_date, prompt: true %>
        </div>

        <div>
            <!-- The 'title' attribute is what shows up when you hover over an element -->
            <%= f.label :is_active %><i class="fas fa-question-circle" title="If the assignment is active, student will be able to view and submit to the assignment."></i>
            <%= f.check_box :is_active %>
        </div>

        <%= f.submit "Post!",class:"ui primary button" %>
    <% end %>

</article>

<script>
    document.addEventListener('DOMContentLoaded', () => {
        document.getElementById("assignment-select").addEventListener("change", (event) => {
            if (document.getElementById(`select-${event.target.value}`)) {
                let assignment = JSON.parse(document.getElementById(`select-${event.target.value}`).dataset.assignment)

                document.querySelector(".assignment-info").innerHTML = `
                    <h2>${assignment.name}</h2>
                    <p>${assignment.description}</p>
                `
            }
        })
    }, false);

</script>

app/views/course_assignments/show.html.erb
<article class="course-assignment-show">
    <h1><%= link_to @course_assignment.course.name, course_path(@course_assignment.course.name) %></h1>

    <h2><%= @course_assignment.assignment.name %></h1>
    <p><%= @course_assignment.assignment.description %></p>

    <p>Assigned <%= distance_of_time_in_words(Time.now, @course_assignment.assign_date) %> ago (<%= @course_assignment.assign_date.strftime('%H:%M %a, %d %b %Y') %>)</p>
    <p>
        <% if @course_assignment.due_date > Time.now %>
            Due in <%= distance_of_time_in_words(Time.now, @course_assignment.due_date) %>
        <% else %>
            Due <%= @course_assignment.due_date %> ago
        <% end %>
        (<%= @course_assignment.due_date.strftime('%H:%M %a, %d %b %Y') %>)
    </p>

    <% if current_user.current_role == "student" %>

        <h2>Your Submission</h2>
        <div class="submission">
            <% submission = find_submission(current_user.current_course_role, @course_assignment) %>
            <% if submission %>
                <div class="submission">
                    <% if submission.respond_to? :submission_url %>
                        Link: <a href=<%= submission.submission_url %>><%= get_host_without_www(submission.submission_url) %></a>
                    <% else %>
                        <p>No URL for this assignment</p>
                    <% end %>
                    <p>
                        Submitted on
                        <%= submission.submission_date.strftime('%H:%M %a, %d %b %Y') %>
                    </p>
                    <%= link_to 'Remove Submition', course_course_assignment_submission_path(submission.course, submission.course_assignment, submission), method: "DELETE", data: {confirm: "Are you sure you want to remove this submission?"} %>
                </div>
            <% else %>
                <p>You haven't submitted anything for this assignment yet.</p>
                <%= link_to 'Submit Something?', new_course_course_assignment_submission_path(@course_assignment.course, @course_assignment) %>
            <% end %>
        </div>

        <% if is_marked?(@course_assignment) %>
            <p>You got: <%= @course_assignment.submissions.find_by(course_role_submitter_id: current_user.id).grade %></p>
            <small>Marked by <%= CourseRole.find(@course_assignment.submissions.find_by(course_role_submitter_id: current_user.id).course_role_marker_id).user.full_name %></small>
        <% else %>
            <p>This assignment has not yet been marked...</p>
        <% end %>
    <% else %>
        <%= link_to 'View Submissions', course_course_assignment_submissions_path(@course_assignment.course, @course_assignment) %>
    <% end %>


    <%= link_to 'Edit', edit_course_course_assignment_path(@course_assignment.course, @course_assignment) %>
    <%= link_to 'Unassign', course_course_assignment_path(@course_assignment.course, @course_assignment), method: :delete, data: {confirm: "Are you sure you want to unassign this?"}%>

</article>