config/routes.rb
Rails.application.routes.draw do
  get 'courses/show'
  get 'courses/archive'


  get 'users/:id/courses', {to: 'users#courses'}
  
  root to: "home#index"
  get 'home/index'

  resources :assignments

  resources :courses do
    resources :course_assignments do
      resources :submissions do
        get "new_grade"
        post "create_grade"
        get "edit_grade"
        patch "update_grade"
        delete "destroy_grade"
      end
    end 
    post "add_attendance"
    end

  resources :users

  get '/users/:id/courses/', {to: "courses#index"}
  get '/users/:id/assignments/', {to: "due_assignments#index"}

  get '/users/:id/submitted_assignments/', {to: "users#submitted_assignments"}
  get '/users/:id/due_assignments/', {to: "users#due_assignments"}

  get '/users/:id/new_role', to: "users#new_role", as: :new_role
  post 'users/:id/create_role', to: "users#create_role", as: :create_role

  resources :assignments

  resources :sessions, only: [:create, :destroy, :new]

  resources :users, only: [:new, :create, :edit, :update, :destroy]

  get '/users/:id/password', { to: "users#password", as: 'password' }
  post '/users/:id/password', { to: "users#update_password", as: 'update_password' }

  get "login", to: "sessions#new"
  get "sign_in", to: "sessions#new"

  get "admin/courses"
  get "admin/users"
  get "admin/archive"

end

app/views/admin/archive.html.erb
<article class="admin-archive">
    <h1>Manage Archived Courses</h1>
    <div>
        <% @archive[:courses].each do |course| %>
            <h3 style="color: <%= course.is_archived ? 'grey' : 'auto' %>">
                <%= course.name %> <small><%= course.is_archived ? "(archived)" : "" %></small>
                <small>
                    <%= link_to 'Edit', edit_course_path(course) %>
                    <%= link_to 'View', course_path(course) %>
                    <%= link_to 'Delete', course_path(course), method: :delete, data: {confirm: "Are you sure you want to delete this course!?"} %>
                </small>
            </h3>
        <% end %>
    </div>

    <h1>Archived Users</h1>

    <% @archive[:course_roles].each do |cr| %>
        <h3 style="color: grey"><%= cr.user.full_name %> (archived <%= cr.role %>)</h3>
    <% end %>

</article>

app/views/admin/courses.html.erb
<article class="admin-courses">
    <h1>Manage Courses</h1>
    <div>
        <% @courses.each do |course| %>
            <h3 style="color: <%= course.is_archived ? 'grey' : 'auto' %>">
                <%= course.name %> <small><%= course.is_archived ? "(archived)" : "" %></small>
                <small>
                    <%= link_to 'View', course_path(course) %>
                    <%= link_to 'Edit', edit_course_path(course) %>
                    <%= link_to 'Delete', course_path(course), method: :delete, data: {confirm: "Are you sure you want to delete this course!?"} %>
                </small>
            </h3>
        <% end %>
    </div>
</article>

app/views/admin/users.html.erb
<article class="admin-users">
        <h1>Manage Users</h1>

        <%= link_to 'Add User', new_user_path %>

        <h2>Unassigned</h2>

        <% @users.select{ |user| user.current_role == nil }.each do |user| %>
            <h4>
                <%= user.full_name %> (<%= user.email %>)
                <small>
                    <%= link_to 'View', user_path(user) %>
                    <%= link_to 'Edit', edit_user_path(user) %>
                    <%= link_to 'Delete', user_path(user), method: :delete, data: {confirm: "Are you sure you want to delete this user!?"} %>
                </small>
            </h4>
        <% end %>

        <h2>Students</h2>
        <% @users.select{ |user| user.current_role == "student" }.each do |user| %>
            <h4>
                <%= user.full_name %> (<%= user.email %>)
                <small>
                    <%= link_to 'View', user_path(user) %>
                    <%= link_to 'Edit', edit_user_path(user) %>
                    <%= link_to 'Delete', user_path(user), method: :delete, data: {confirm: "Are you sure you want to delete this user!?"} %>
                </small>
            </h4>
        <% end %>

        <h2>Instructors</h2>
        <% @users.select{ |user| user.current_role == "instructor" }.each do |user| %>
            <h4>
                <%= user.full_name %> (<%= user.email %>)
                <small>
                    <%= link_to 'View', user_path(user) %>
                    <%= link_to 'Edit', edit_user_path(user) %>
                    <%= link_to 'Delete', user_path(user), method: :delete, data: {confirm: "Are you sure you want to delete this user!?"} %>
                </small>
            </h4>
        <% end %>

        <h2>Admins</h2>
        <% @users.select{ |user| user.current_role == "admin" }.each do |user| %>
            <h4>
                <%= user.full_name %> (<%= user.email %>)
                <small>
                    <%= link_to 'View', user_path(user) %>
                    <%= link_to 'Edit', edit_user_path(user) %>
                    <%= link_to 'Delete', user_path(user), method: :delete, data: {confirm: "Are you sure you want to delete this user!?"} %>
                </small>
            </h4>
        <% end %>

</article>