config/routes.rb
Rails.application.routes.draw do
  get 'courses/show'
  get 'courses/archive'


  get 'users/:id/courses', {to: 'users#courses'}
  
  root to: "home#index"
  get 'home/index'

  resources :assignments

  resources :courses do
    resources :course_assignments do
      resources :submissions do
        get "new_grade"
        post "create_grade"
        get "edit_grade"
        patch "update_grade"
        delete "destroy_grade"
      end
    end 
    post "add_attendance"
    end

  resources :users

  get '/users/:id/courses/', {to: "courses#index"}
  get '/users/:id/assignments/', {to: "due_assignments#index"}

  get '/users/:id/submitted_assignments/', {to: "users#submitted_assignments"}
  get '/users/:id/due_assignments/', {to: "users#due_assignments"}

  get '/users/:id/new_role', to: "users#new_role", as: :new_role
  post 'users/:id/create_role', to: "users#create_role", as: :create_role

  resources :assignments

  resources :sessions, only: [:create, :destroy, :new]

  resources :users, only: [:new, :create, :edit, :update, :destroy]

  get '/users/:id/password', { to: "users#password", as: 'password' }
  post '/users/:id/password', { to: "users#update_password", as: 'update_password' }

  get "login", to: "sessions#new"
  get "sign_in", to: "sessions#new"

  get "admin/courses"
  get "admin/users"
  get "admin/archive"

end

app/models/user.rb
require "csv"

class User < ApplicationRecord
  has_secure_password
  has_many :course_roles, dependent: :destroy\

  def full_name
    "#{first_name} #{last_name}".strip
  end

  def archived_courses
    self.course_roles.map(&:course).select { |course| course.is_archived == true }
  end

  def active_courses
    self.course_roles.map(&:course).select { |course| course.is_archived == false }
  end

  def current_role
    self.is_admin ? "admin" : current_course_role&.role
  end

  def current_course_role
    self.is_admin? ? CourseRole.new(course: Course.all.sample, user: self, role: "admin") : self.course_roles.where(is_archived: false).first
  end

  def self.import_from_CSV(filepath)
    data = CSV.read(filepath, headers: true)
    data.each do |row|

      # Remove excess whitespace
      row.map { |key, value| [key, value ? value.strip : value] }.to_h

      user_data = {
        email: row["email"],
        first_name: row["first_name"],
        last_name: row["last_name"],
        password: row["password"],
        img_url: row["img_url"],
        is_admin: row["role"] == "admin",
        status: row["status"]
      }
      
      user = User.create(user_data)
      
      unless row["role"] == "admin" || !user
        course = nil
        
        # If a number is given, check by id
        # Otherwise try to find it by name
        if row["course"].match(/\d+/)
          course = Course.find_by(id: row["course"])
        else
          course = Course.find_by(name: row["course"])
        end
          
        if course
          CourseRole.create(
            role: row["role"],
            user_id: user.id,
            course_id: course.id,
            is_archived: false
          )
        else
          puts "WARNING USER #{row['email']} WAS NOT CREATED. Check that your course is a valid id or name"
          # Don't create a user without a role
          user.destroy
        end

      end
      
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:edit, :show, :update, :password, :update_password]

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end

  end

  def show
    @user = user.find(params[:id])
  end

  def edit
    @user = current_user
  end

  

  def update
   
    if @user.update user_params
      redirect_to root_path
      flash[:notice] = 'User information updated'
    else
      render :edit
    end
  end

  def password
   
  end

  def update_password
   
    
    if @user&.authenticate params[:user][ :current_password ]
      
      if @user.update user_params
        
          flash[:success] = "Password updated"
          redirect_to root_path
        
      else
          flash[:danger] = @user.errors.full_messages.join(', ')
          redirect_to password_path(@user)
      end
    else
      flash[:danger] = "You've entered an invalid current password"
      redirect_to password_path
    end

   
  end

  def destroy
    flash[:notice] = "User deleted"
    @user.destroy
    redirect_to root_path

  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :status, :img_url, :is_admin)
  end

  def find_user
    @user = User.find params[:id]
  end




end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_attendance.html.erb
<%= form_with url: "/course/#{@course_role[0].course}/add_attendance", method: :post, local: true do |f| %>
    <% f.hidden_field :date, @date %>
    <% @course_roles.each do |user| %>
    <h2><%= user.user.full_name %></h2>
    AM<%= f.check_box "data-AM-#{user.id}" %>
    PM<%= f.check_box "data-PM-#{user.id}" %>
    TA<%= f.check_box "data-TA-#{user.id}" %>
    <% end %>
<% end %>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
    <ul>
        <% @user.errors.full_messages.each do |msg|%>
        <li><%=msg%></li>
        <%end%>
    </ul>
<%end%>



<%= form_with model: @user, local: true do |f|%>
    <div class="ui equal width form">
    <div>
        <%=f.label :img_url %>
        <%=f.text_field :img_url %>
    </div>
    <div>
        <%=f.label :first_name %>
        <%=f.text_field :first_name %>
    </div>
    <div>
        <%=f.label :last_name %>
        <%=f.text_field :last_name %>
    </div>
    <div>
        <%=f.label :email %>
        <%=f.email_field :email %>
    </div>
   

    <%if admin_signed_in?%>

    <div>
        <%= f.label :active %><br />
        <%= f.label :active, "Active", :value => "true"  %>
        <%= f.radio_button :active, true %>
        <%= f.label :active, "Inactive", :value => "false" %>
        <%= f.radio_button :active, false, :checked => true %>
    </div>
    </div>
    <%= f.submit "Save",class:"ui primary button" %>
    <%= link_to 'Delete', user_path(@user), method: :delete, data: {confirm: "Are you sure?"} %>
    <% end %>

    <p>

    </div>
    <%= f.submit "Update Account", class:"ui primary button" %>

    <%#= link_to 'Delete', user_path(@user), method: :delete, data: {confirm: "Are you sure?"} %>

    <%= link_to "Update Password", password_path(current_user) %> 
  
   
    
<% end %>

app/views/users/courses.html.erb
<p>User Courses</p>

<div>
  <div>
    <h2>Active</h2>
      <% @active_courses.each do |course| %>
        <div>
            <%= course.id %>
            <%= course.name %>
            <%#= link_to user.full_name, user_path(user)%>
        </div>
        <% end %>
      </div>  
  </div>


  <div>
    <h2>Archived</h2>
    <% @archived_courses.each do |course| %>
      <div>
          <%= course.id %>
        <%= course.name %>
        <%#= link_to user.full_name, user_path(user)%>
      </div>
    <% end %>
  </div>  
</div>

app/views/users/due_assignments.html.erb
<article class="user-due-assignments">
    <h1>Due Assignments </h1>

    <% @assignments.each do |assignment| %>
        <h2>Assignment: <%= assignment.assignment.name %></h2>
        <h3>Course: <%= assignment.course.name %></h3>
        <h3>
            <% if assignment.due_date > Time.now %>
                <p>Due in <%= distance_of_time_in_words(Time.now, assignment.due_date) %> </p>
            <% else %>
                <p>Due <%= assignment.due_date %> ago</p>
            <% end %>
        </h3>
        <%= link_to 'View details...', course_course_assignment_path(assignment.course, assignment) %>
    <% end %>

</article>

app/views/users/edit.html.erb
<h1>Edit User Profile</h1>
<%= render "form"%>

app/views/users/index.html.erb
<div class="ui relaxed divided list">
<div class="item">
<i class="large github middle aligned icon"></i>
<div class="content">
<h2>List All Students</h2>

    <% @users.each do |user| %>
        <%= user.first_name %><br/>
        <%= user.last_name %><br/>
        <%= user.role %><br/>
        <%= user.email %><br/>
        <%if admin_signed_in?%>
            <%= link_to 'Edit', edit_user_path(@user) %>
            <%= link_to 'Delete', user_path(@user), method: :delete, data: {confirm: "Are you sure?"} %>
        <%end%>
    <% end %>

  </div>
  </div>
</div>

app/views/users/new.html.erb
<h1>Create New User</h1>

<% if @user.errors.any? %>
    <ul>
        <% @user.errors.full_messages.each do |msg|%>
        <li><%=msg%></li>
        <%end%>
    </ul>
<%end%>

<%if admin_signed_in?%>

<%= form_with model: @user, local: true do |f|%>
    <div class="ui equal width form">
    <div>
        <%=f.label :img_url %>
        <%=f.text_field :img_url %>
    </div>
    <div>
        <%=f.label :first_name %>
        <%=f.text_field :first_name %>
    </div>
    <div>
        <%=f.label :last_name %>
        <%=f.text_field :last_name %>
    </div>
    <div>
        <%=f.label :email %>
        <%=f.email_field :email %>
    </div>
  
    <div>
        <%=f.label :password %>
        <%=f.password_field :password %>
    </div>
    <div>
        <%=f.label :password_confirmation %>
        <%=f.password_field :password_confirmation %>
    </div>

    <p>
   
    </div>

   

    <%= f.submit "Save",class:"ui primary button" %>
   
  
    <% end %>
    
<% end %>

app/views/users/new_role.html.erb
<article class="new-role">
    <%= form_for(@role, url: create_role_path(@user), method: :post) do |f| %>
    <div>    
        <%= f.label :role %>
        <%= f.select :role, ["student", "teacher"] %>
    </div>
    <div>
        <%= f.label :course_id %>
        <%= f.select :course_id, @courses.collect {|c| [c.name, c.id] } %>
    </div>

    <%= f.submit "Add role "%>

    <% end %>
      
</article>

app/views/users/password.erb
<% if @user.errors.any? %>
<ul>
    <% @user.errors.full_messages.each do |msg|%>
    <li><%=msg%></li>
    <% end %>
</ul>

<%end%>

<h1>Edit User</h1>

<%= form_with url: update_password_path, local: true do |f| %>

<div>
  <%=f.label :current_password %>
  <%=f.password_field :current_password %>
</div>

<div>
  <%=f.label :new_password %>
  <%=f.password_field :password %>
</div>
<div>
  <%=f.label :password_confirmation %>
  <%=f.password_field :password_confirmation %>
</div>

<%= f.submit "Update Password" %>

<% end %>

app/views/users/password.html.erb
<h1>Edit User</h1>

<%= form_with model: @user, url: update_password_path, local: true do |f| %>

  <div>
  <%=f.label :current_password %>
  <%=f.password_field :current_password %>
</div>

<div>
  <%=f.label :password %>
  <%=f.password_field :password %>
</div>
<div>
  <%=f.label :password_confirmation %>
  <%=f.password_field :password_confirmation %>
</div>

<%= f.submit "Update Password" %>

<% end %>

app/views/users/show.html.erb
<h4>User Detail</h4>

<div>

<%= image_tag "#{@user.img_url}"%>

<p> First name:
<%= @user.first_name %> </p>

<p> Last name: 
<%= @user.last_name %> </p>

<p> Role: 
<%= @user.current_role %> </p>

<p> Courses:
  <% @user.course_roles.map(&:course).each do |course|  %>
  <p> - <%= link_to course.name, course_path(course) %> </p>
<% end %>

<p> Email: 
<p> <%= @user.email %> </p>

<p> Status:
  <% if @user.status %>
    active
  <% else %>
    inactive
  <% end %>
  </p>




</div>

<%= link_to 'Add Role', new_role_path(@user) %>
<%= link_to "Edit Profile", edit_user_path(@user) %>
<%= link_to "Change Password", password_path(@user)%>

app/views/users/submitted_assignments.html.erb
<article class="submitted-assignments">
    <% @assignments.each do |assignment| %>
            <h2>Assignment: <%= assignment.assignment.name %></h2>
            <h3>Course: <%= assignment.course.name %></h3>
            <h3>
                <% if assignment.due_date > Time.now %>
                    <p>Due in <%= distance_of_time_in_words(Time.now, assignment.due_date) %> </p>
                <% else %>
                    <p>Due <%= assignment.due_date %> ago</p>
                <% end %>
            </h3>
            <%= link_to 'View details...', course_course_assignment_path(assignment.course, assignment) %>
        <% end %>
</article>

app/views/users/usercourse.html.erb
<div class="ui card">
    <div class="content">
    <% @active_courses.each do |active_course|%>
        <div>
        <h3>Course: <%= @course.name %></h3>
        <h3>Curriculum:<%= @course.description %></h3>
        <p>Start Date: <%= @course.start_date %></p>
        <p>End Date: <%= @course.end_date %></p>
        <p>Status: <%= @course.status %></p>
        </div>
    <%end%>

    <%if admin_signed_in?%>
    <%= link_to 'Edit', edit_course_path(@course) %>
    <%= link_to 'Delete', course_path(@course), method: :delete, data: {confirm: "Are you sure?"} %>
    <%end%>
    </div>
</div>


<div class="ui card">
     <div class="content">
    <% @inactive_course.each do |inactive_course|%>
      <div>
        <h3>Course: <%= @course.name %></h3>
        <h3>Curriculum:<%= @course.description %></h3>
        <p>Start Date: <%= @course.start_date %></p>
        <p>End Date: <%= @course.end_date %></p>
        <p>Status: <%= @course.status %></p>
        </div>
    <% end %>

    <%if admin_signed_in?%>
    <%= link_to 'Edit', edit_course_path(@course) %>
    <%= link_to 'Delete', course_path(@course), method: :delete, data: {confirm: "Are you sure?"} %>
    <%end%>
    </div>
</div>