config/routes.rb
Rails.application.routes.draw do
  get 'courses/show'
  get 'courses/archive'


  get 'users/:id/courses', {to: 'users#courses'}
  
  root to: "home#index"
  get 'home/index'

  resources :assignments

  resources :courses do
    resources :course_assignments do
      resources :submissions do
        get "new_grade"
        post "create_grade"
        get "edit_grade"
        patch "update_grade"
        delete "destroy_grade"
      end
    end 
    post "add_attendance"
    end

  resources :users

  get '/users/:id/courses/', {to: "courses#index"}
  get '/users/:id/assignments/', {to: "due_assignments#index"}

  get '/users/:id/submitted_assignments/', {to: "users#submitted_assignments"}
  get '/users/:id/due_assignments/', {to: "users#due_assignments"}

  get '/users/:id/new_role', to: "users#new_role", as: :new_role
  post 'users/:id/create_role', to: "users#create_role", as: :create_role

  resources :assignments

  resources :sessions, only: [:create, :destroy, :new]

  resources :users, only: [:new, :create, :edit, :update, :destroy]

  get '/users/:id/password', { to: "users#password", as: 'password' }
  post '/users/:id/password', { to: "users#update_password", as: 'update_password' }

  get "login", to: "sessions#new"
  get "sign_in", to: "sessions#new"

  get "admin/courses"
  get "admin/users"
  get "admin/archive"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        @courses = current_user.course_roles.map(&:course)
        @assignments = @courses.map(&:course_assignments).flatten

     role = current_user.current_role

        if role === "student"
            render :student_homepage
        elsif role === "admin"
            @courses = Course.all
            @users = User.all
            render :admin_homepage
        elsif role === "instructor"
            render :instructor_homepage
        end
    end
end

app/views/home/_assignments.html.erb
<div class='card'>
  <div class='card-header'>
    <h2>Pending Assignments</h2>
  </div>
  <div class='panel-container'>
  <% @assignments[0..5].each do |assignment| %>
  <div class="card-content" onClick="() => {window.location.href = '/course_assignments/<%= assignment.id %>'}">
    <h3><%= link_to assignment.assignment.name, assignment_path(assignment) %></h3>
      <small> <%= assignment.course.name %></small>
    <h3>
      <% if assignment.due_date > Time.now %>
        <p>Due in: <%= assignment.due_date.strftime('%H:%M - %d %b %Y') %> </p>
      <% else %>
        <p>Due on: <%= assignment.due_date.strftime('%H:%M - %d %b %Y') %> ago</p>
      <% end %>
    </h3>
  </div>
  <% end %>
  </div>
</div>

app/views/home/_courses.html.erb
<div class='card'>
    <div class='card-header'>
      <h2>Courses</h2>
    </div>
    <div class='card-content'>
      <% @courses.map do |course| %>
        <div class="course-item">
          <h3><%= link_to course.name, course_path(course)%></h3>
        </div>
      <% end %>
    </div>
</div>

app/views/home/admin_homepage.html.erb
<article class="admin-homepage">
  <div class='admin-panel'>    
    <div class='panel-header'>
      <h1>Manage Users</h1>
    </div>
    <div class='panel-row'>
    <div class='panel'>
      <div class='panel-header'>
        <h2>Students</h2>
      </div>
      <div class='panel-container'>
        <% @users.select{ |user| user.current_role == "student" }.each do |user| %>
          <div class='panel-content'>
            <h4>
              <%= user.full_name %> (<%= user.email %>)
              <div class='button'>
                <%= link_to 'View', user_path(user) %>
                <%= link_to 'Edit', edit_user_path(user) %>
                <%= link_to 'Delete', user_path(user), method: :delete, data: {confirm: "Are you sure you want to delete this user!?"} %>
              </div>
            </h4>
          </div>
        <% end %>
      </div>
    </div>
    <div class='panel'>
      <div class='panel-header'>
        <h2>Instructors</h2>
      </div>
      <div class='panel-container'>
        <% @users.select{ |user| user.current_role == "instructor" }.each do |user| %>
          <div class='panel-content'>
            <h4>
              <%= user.full_name %> (<%= user.email %>)
              <div class='button'>
                <%= link_to 'View', user_path(user) %>
                <%= link_to 'Edit', edit_user_path(user) %>
                <%= link_to 'Delete', user_path(user), method: :delete, data: {confirm: "Are you sure you want to delete this user!?"} %>
              </div>
            </h4>
          </div>
        <% end %>
      </div>
    </div>
    <div class='panel'>
      <div class='panel-header'>
        <h2>Admins</h2>
      </div>
      <div class='panel-container'>
        <% @users.select{ |user| user.current_role == "admin" }.each do |user| %>
          <div class='panel-content'>
            <h4>
              <%= user.full_name %> (<%= user.email %>)
              <div class='button'>
                <%= link_to 'View', user_path(user) %>
                <%= link_to 'Edit', edit_user_path(user) %>
                <%= link_to 'Delete', user_path(user), method: :delete, data: {confirm: "Are you sure you want to delete this user!?"} %>
              </div>
            </h4>
          </div>
        <% end %>
      </div>
    </div>
    </div>
  </div>
  <div class='admin-panel'>
    <div class='panel-header'>
      <h1>Manage Courses</h1>
    </div>
    <div class='panel-container'>
      <% @courses.each do |course| %>
        <div class='panel-content'>
          <h3>
            <%= course.name %>
            <div class='button'>
              <%= link_to 'View', course_path(course) %>
              <%= link_to 'Edit', edit_course_path(course) %>
              <%= link_to 'Delete', course_path(course), method: :delete, data: {confirm: "Are you sure you want to delete this course!?"} %>
            </div>
          </h3>
        </div>
      <% end %>
    </div>
  </div>
</article>

app/views/home/courseview.html.erb
<div class="ui card">
    <% @active_courses.each do |active_course|%>
        <div>
        <h3>Course: <%= @course.name %></h3>
        <h3>Curriculum:<%= @course.description %></h3>
        <p>Start Date: <%= @course.start_date %></p>
        <p>End Date: <%= @course.end_date %></p>
        <p>Status: <%= @course.status %></p>
        </div>
    <%end%>

    <%if can?(:crud, @course)%>
    <%= link_to 'Edit', edit_course_path(@course) %>
    <%= link_to 'Delete', course_path(@course), method: :delete, data: {confirm: "Are you sure?"} %>
    <%end%>
</div>

<div class="ui card">
    <% @inactive_course.each do |inactive_course|%>
      <div>
        <h3>Course: <%= @course.name %></h3>
        <h3>Curriculum:<%= @course.description %></h3>
        <p>Start Date: <%= @course.start_date %></p>
        <p>End Date: <%= @course.end_date %></p>
        <p>Status: <%= @course.status %></p>
        </div>
    <% end %>

    <%if can?(:crud, @course)%>
    <%= link_to 'Edit', edit_course_path(@course) %>
    <%= link_to 'Delete', course_path(@course), method: :delete, data: {confirm: "Are you sure?"} %>
    <%end%>
</div>

app/views/home/index.html.erb
<div class='card-tier'>
  <div class='card'>
    <div class='card-header'>
      <h1>My Courses</h1>
    </div>
    <div class="card-content">
      <%#=@course.name%>
      <%#=@course.description%>
    </div>
  </div>
  <div class='card'>
    <div class='card-header'>
      <h1>Assignments</h1>
    </div>
    <div class="card-content">
      <%#=@course.name%>
      <%#=@course.description%>
    </div>
  </div>
</div>

app/views/home/instructor_homepage.html.erb
<article class="instructor-homepage">
  <div class='card-tier'>
    <%= render "courses" %>
    <%= render "assignments" %>
  </div>
  <div class='card-tier'>
    <%= link_to 'Create New Assignment', new_assignment_path, class:"ui pink basic button" %>
    <%= link_to 'Click to View All Assignments!', assignments_path, class:"ui purple basic button" %>
  </div>
  <div class='card-tier'>
    <%= render 'layouts/calendar' %>
  </div>
</article>

app/views/home/profile.html.erb
<div class='card-tier'>
  <div class='card'>
    <div class='card-header'>
      <h1>You want to change your profile setting?</h1>
    </div>
    <div class='card-content'>
      <% if @user.errors.any? %>
        <ul>
          <% @user.errors.full_messages.each do |msg|%>
          <li><%=msg%></li>
          <%end%>
        </ul>
      <%end%>
      <%= form_with model: @user, url:'', local: true do |f|%>
    </div>
  </div>
</div>






<div class="form-group">
<%= f.label :current_password%>
<%= f.text_field :current_password, class:"form-control"%>
</div>
<div class="form-group">
<%= f.label :password%>
<%= f.text_field :password, class:"form-control", required: true%>
</div>
<div class="form-group">
<%= f.label :password_confirmation%>
<%= f.text_field :password_confirmation, class:"form-control", required: true%>
</div>


<%= f.submit "Update Password", class:"btn btn-outline-primary"%>
<%end%>

app/views/home/student_homepage.html.erb
<article class="student-homepage">
  <div class='card-tier'>
    <%= render 'courses' %>
    <%= render 'assignments' %>
  </div>
  <div class='card-tier'>
    <%= render 'layouts/calendar' %>
  </div>
</article>